# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Daverin Nadesan
title: Artist | Software Generalist | 3D Generalist
email: daverin@beamm.co
phone: "+27815544084"
# website: www.rsdata.co.za

darkmode: false

# Social links
# twitter_username: jekyllrb
# github_username:  https://github.com/rsdatatechnologies?tab=repositories
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: https://www.instagram.com/daverinnadesan
# linkedin_username: https://www.linkedin.com/in/daverin-nadesan/
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/download-removebg-preview-outline.png
about_content: | # this will include new lines to allow paragraphs
  I am an artist and a generalist at my core. I create value in the gaps between the industries that I am familiar with - Augmented Reality,
  3D Animation, Web Development, Mobile App Development, and Cloud Architecture. 

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
more_title: Skills #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs

  Languages:
  - Python
  - Dart
  - C#
  - Javascript
  - C++
  - Java
  
  Frameworks:
  - Unity
  - Flutter
  - Kubernetes
  - FastAPI (Starlette)
  - React
  - Angular

  3D Design Software:
  - Blender
  - Substance Painter

  2D Design Software:
  - Photoshop
  - Gimp
  - Inkscape

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
